# Generated by Django 6.0.7 on 2026-08-09 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SuperSchool', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='grade_level',
            field=models.CharField(default='Logika', max_length=50, verbose_name='Клас'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(default='Програмування', max_length=100, verbose_name='Назва предмета'),
        ),
    ]
