# Generated by Django 6.0.7 on 2026-08-09 09:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SuperSchool', '0002_alter_student_grade_level_alter_subject_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grade',
            name='comment',
        ),
        migrations.AddField(
            model_name='student',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Опис'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='score',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Оцінка'),
        ),
    ]
